### ISSUE TITLE
Changed files doesn't refresh after a commit

### ISSUE THREAD

**Issue by PureKrome** [jzoss/Git-Source-Control-Provider#10]
If I do _not_ tick/check all the items in my commit list, then commit, the commit list goes empty and doesn't refresh. Then clicking the refresh button _also_ doesn't refresh the list.

Repo:

- Modify a few files (i had about 20)
- Tick all all but 2 files. Then click COMMIT.
- File-list goes empty. Those 2 unticked files are still not showing.

:(

**Comment by teebee76** [comment]
Not happening on my setup. 

Git Source Control Provider v 1.4.1 
Git Extensions 1.0.5
Git 2.6.3 (64bit)

when checking only one item and pressing commit, the entire list goes blank at first, but then the changed files reappear after about 1 sec.

**Comment by PureKrome** [comment]
Git source control provider v 1.4.1 also.

I think this might have something to do with a `branch-switch` ? maybe.. i think when i switched branches .. the entire `pending changes` window still thinks i'm in the other branch?

hmm.. (i'm trying to find ways to get a consistent repo of this).

**Comment by PureKrome** [comment]
Not sure if this is related (as I'm trying to source more info)..

But check out my window - there's _no_ branch name there..

but i'm definitely in a branch (as seen by tortoise git).

![image](https://cloud.githubusercontent.com/assets/899878/11519650/0693a8f2-98f0-11e5-939e-948a54b539f4.png)

**Comment by jzoss** [comment]
Hey @PureKrome and @teebee76  can you try this new beta release.. https://github.com/jzoss/Git-Source-Control-Provider/releases/tag/1.4.1.1 . Not 100% done yet.. but I think its getting there..

**Comment by jzoss** [comment]
@PureKrome @teebee76 .. Thanks for you feedback.. 

So I think I have it sorted or at least I'm moving in the right direction.  It was a b*tch to track down the cause, because it had to do with timing that took me a while to figure that out, then figure out how to recreate it in a debugger. 
So here was the issue. It was caused by a few things. 

1.	The plugin uses a FileSystemWacher, so when a file changes the status in VS can be updated. FileSystemWatcher has a tendency to publish multiple change events when you change a file.. 

2.	I think because of the multiple events, the previous developer setup it up so that when ever a file event happened, it would reset the auto update loop, and you would have to wait the delay before the git status (Glyphs) in VS will update. I think this could cause issues regardless, but then I came along, and really killed it because…

3.	I noticed after the 1.3.1 release that  the git plugin could cause VS to slow down.. it was because of how it was using git.. it got status and many other git functions but calling git on the command line and parsed the command line output.. It was not as fast, and because of a few issues was throwing loads of exceptions. So.. I decided it was worth a try to start converting to libgit2sharp.

4.	This worked well! I am converting bit by bit to using libgit2sharp.. I am probably about 50% but thing are moving. and it is a lot faster than before. I still think this is the way forward… and all was well until….

5.	I fixed the pending changes, updated to use libgit2sharp and then funny stuff started to happen.. Not was working .. and it took forever to update.  Well, it turns out it because as I asking the repo for the diff, behind the scene libgit2sharp was updating the blob file in the .git folder.. Now there is nothing wrong with that, but that was causing the FileSystemWatcher to cause an event and rest the wait for update to 500 ms..  The diff either from the PendingChanges window or solution integration was almost always running faster than 500 ms.. so the UI update would never run.

6.	To make matters slightly worse … as you might imagine, during debugging .. when I throw in break points. everything worked just fine.   GAAA… 

Sorry to go off.. but I wanted to vent a bit  Anyway now that I know what it is, I can finish trying to fix it..

**Comment by PureKrome** [comment]
@jzoss dude. LOVE the detailed brain dump :+1: Respect :+1: 

I feel your pain as i'm doing some debugging on some _really_ simple linq stuff today and .. well.. it's not working because i need to be jumping at the right time, turning around at the right time and probably singing three songs at the same time - to get the repo conditions right :/

Keep fighting the good fight sir! we have your back!

**Comment by teebee76** [comment]
I'm glad you figured it out, and don't have to stay awake at night thinking about it. It's always a great relief when you finally crack that problem wide open :+1:  good working, I've also had my battles with the debugger, and sometimes everything just works fine on the dev machine when doing the debugging while it's breaking on the production server.

**Comment by jzoss** [comment]
@PureKrome and @teebee76 I have another beta release .. Please check it out.. I tested it a bit.. but you guys seem to find my bugs much better than I do. 1.4.2 Beta 1

**Comment by PureKrome** [comment]
Installed beta ([from here](https://github.com/jzoss/Git-Source-Control-Provider/releases)) and will be using/testing it.

**Comment by jzoss** [comment]
@PureKrome and @teebee76  Just wanted again thanks for your support. I love do the brain dumps.. Makes me think about the problem a bit. Anyway.. I have had much better luck with the latest build. I have not heard from anyone with more bugs yet... so.. that's either good.. or proof it's Friday!
