### ISSUE TITLE
What is the point in having 2 separate projects for this?

### ISSUE THREAD

**Issue by NightOwl888** [jzoss/Git-Source-Control-Provider#13]
Maybe there is some compelling reason why the author of the original [Git Source Control Provider](https://visualstudiogallery.msdn.microsoft.com/63a7e40d-4d71-4fbb-a23b-d262124b8f4c) started a separate project called [Git Tools](http://yysun.github.io/git-tools/) to replace Git Source Control Provider in VS2015, and you started a separate branch of the original Git Source Control Provider to support VS2015, but I am not seeing what that reason is.

Is there something preventing you from combining your efforts on the [Git Tools](https://github.com/yysun/git-tools) (official) project? Is there something that this project is supposed to provide that is not present in Git Tools?

According to the [Git Tools Readme](https://github.com/yysun/git-tools):

> The same set of Git tools were developed in Git Source Control Provider for Visual Studio 2008-2013. Since Visual Studio 2013, Microsoft has built Microsoft Git provider. There is only one source control provider can beused in Visual Studio at a time. This extension is a modification of Git Source Control Provider. It removed the source control provider and contains the Git tools only, so that it makes the Git tools compatible with Microsoft Git provider.

Unfortunately, both projects seem to have lots of bugs at the moment. It would be nice if efforts were combined on Git Tools (the official one) to fix the bugs instead of having two ever-diverging projects.

Admittedly, I was confused why the original Git Source Control Provider project didn't have support for VS2015 - perhaps there just needs to be clearer documentation that users of VS2015 need to install the one called Git Tools. Right now that is not clear at all.

**Comment by teebee76** [comment]
Just to be clear I am not a developer on this project, secondly I was not aware of this other project you mentioned, and so were probably not the developer of this project either. 
If you look at the activity for the other project, I am by that alone going to stick with this one, and if need be contribute to this branch, which I suppose will be more recognizable by developers switching to vs2015
This project has, at least at the moment, rapid changes and releases, and no showstopper-bugs preventing me from using it like I did before. 

What advantages will I have if I switch to the other so-called "official" project, and when you tell me it has bugs, what hopes do I have that they will be fixed when the project hasn't shown movement in almost a year ?

**Comment by teebee76** [comment]
Just had to test it ...

Installed the extension, and actually it's quite nice. I like some of the features like the console-tab in the changes-window , maybe @jzoss can snatch some of the code and make that possible in this version as well, or Like you mentioned before merge the 2 projects and create one ultimate bug-free version :) 

![image](https://cloud.githubusercontent.com/assets/5390116/11561591/bb0ed440-99c8-11e5-9aa3-f62d9b70df92.png)

**Comment by jzoss** [comment]
@NightOwl888 So I am with you.. I started out by just asking the original dev if he was planning on adding solution integration to his new project.. He said no. So I started doing this. My first failed refactor actually brought in all his code, but there was too many changes.. .and the code was already a mess, I couldn't figure it out.. I did however take the Git integration project from that code.. and started to use that.. I have been focusing on making my updated git integration solid, because this will make new features much easier to add.  I was always sorta planning to take over what that project did if I got the chance. @teebee76 I know you are not the developer, but you could join me! You don't know the power of the dark side!

**Comment by NightOwl888** [comment]
Well, truth be told I don't really care which project is the authoritive one.

The Git Tools project has this going for it:

1. Original Author
2. Works along side the Microsoft Git Provider

And of course this one has:

1. Active Development

All of these are important things. In theory, making a project to work along side the Microsoft Git Provider is great because the Git Provider supports push and pull, meaning you don't need the command line as frequently.

On the other hand, it is also important to have active development to weed out inevitable bugs.

But has any attempt been made to petition @yysun to see if becoming a collaborator on that project is possible? Also, if the code is not understandable, is it possible to have him write up some documentation?

At the very least it would make sense to try fixing one of the open issues and submit a pull request. Maybe the development hasn't been active in 10 months, but that doesn't necessarily mean that bug fixes won't be accepted via pull request.

Personally, I have only experienced [one issue](https://github.com/yysun/git-tools/issues/11) with Git Tools - for some reason the comparision window doesn't take into consideration the line endings (at least not in VB.NET, it seems to work fine with a C# project). But then, I haven't tested either of these providers very well because I am not using VS2015 very much yet, and this is but one issue preventing me from making the upgrade to VS2015 on my main projects.

@jzoss - I have already been to the dark side.

- [MvcSiteMapProvider](https://github.com/NightOwl888/MvcSiteMapProvider) - worked with original owner to lead development on v4 as a collaborator
- [Dirty Forms](https://github.com/snikch/jquery.dirtyforms) - worked with the original owner to become a collaborator
- [BoboBrowse.Net](https://github.com/NightOwl888/BoboBrowse.Net) - tried to get the original owner to accept my help, and failed, so created my own repo (that turned out to be a full port of a much later version than [the original](https://bobo.codeplex.com/))

I feel your pain, but feel it is always better to push contributions than to create a fork for public consumption.

**Comment by jzoss** [comment]
@NightOwl888 Question.. I'm just wondering.. why you drop into the command line so often? I just use TortoiseGit and I hardly ever use the command line.. Anyway.. true this does not work at the sam etime as the Microsoft Git Provider.. but ii gives the whole TGit interaction. I mean.. I guess I coudl try and make it work both with and without the MS Git.. Not sure HOW to do it both ways..

**Comment by NightOwl888** [comment]
> Question.. I'm just wondering.. why you drop into the command line so often?

1. I had read when I started using Git that TortoiseGit was a bit buggy.
2. I frequently make a commit and then realize there should have been some additional edits to that commit. It is really handy using Git interactive mode to merge commits or just to fix up commit messages (especially when you consider that if you put `Closes #3` or `Fixes #3` into the commit message, the issue will be closed automatically).

Frankly, I probably won't give up the command line just because I can push and pull from Visual Studio, but it would at least make those common tasks more accessible.

**Comment by NightOwl888** [comment]
I guess another reason I use the command line is because that is usually what the advice is on Stack Overflow.

**Comment by yysun** [comment]
As owner of the two projects, I am open to all options. Let's discuss and decide.

First a bit history. The GitScc project started and worked in VS2008, when VS extension was very difficult to make. It took a lot of time from contributors to make it through VS2010, VS2012, and VS2013. Eventually, it became less maintained due to my time limitation for the project.

Starting VS 2013 and VS 2015, Microsoft Git Provider has been improving. I just want to do what Microsoft Git Provider does not have: A Git changes window (that can commit file chunks some day in the future) and a integrated command line console. So I started the Git Tools project. But again, I had limited time, so it's not going well. I admit.

I would prefer focus on developing the Git Tools project. Contributors are welcome. But if you like the Git Source Control Provider, I make accept contributors too. For sure I will answer any questions for you to understand the code.

**Comment by jzoss** [comment]
@yysun I'm all for combining our efforts. But @NightOwl888  they are actually different the plugins. The new one @yysun is working on is not  a scc provider. That's just fine, but some people prefer to the experience of the scc provider you get when using Tortoisegit. 

@yysun I want to say, I have really done much work on the UI since I forked it from your repo. One of the first things I did do, was to port over the GitApi2 from your Git Tools project.. Then I switched over to using that... And I have been focusing much of my time in that project.. updating it to use libgit2sharp. I've managed to get some nice performance gains. 

So.. if we can figure out a way to have the Git Tools always there, and let them chose to use the Git SCC provider and finish the conversion to libgit2sharp I think it would be very solid.

**Comment by yysun** [comment]
@jzoss thanks for your help on this project. I liked the idea to have both projects share same core based on libgit2sharp. If you want to merge into the master branch, I can merge your pull request or just make you as contributor so that you can merge it. Finally you can send me the compiled installer, I will push to the vs extension gallery.

**Comment by ddobrev** [comment]
@yysun @jzoss it's great that you want to merge the code and join forces. However, I think the MS Git Source Control Provider has a bug. When a Git repository is checked out within another Git repository, the MS provider only detects the parent repository and any commands do not work for files from the child repository. This is actually the only reason I use this project because I otherwise think that reusing MS's provider makes more sense.

**Comment by PureKrome** [comment]
Be nice if both became one. 

I tried using the official GitHub pluging for VS (found in the nasty Team Explorer) window .. and it was just too confusing for little ole me :(

I can't live without the DIFF window, when I click on all my changed/new files in the file-list window of GSCP.

**Comment by jzoss** [comment]
@PureKrome You hit the nail on the head.. I will not merge if it means the scc provider goes away. I like using the same git interface inside and outside visual studio. 

The truth is, that these 2 plugins are different now.. One is a SCC provider the other is not. If I can find a way to give you the git tool and let you use the built in git provider, but still be able to enable the git GSCP then I would be ok with that, but I am not sure when I will have the time yet to invest in that. Since this is sorta a hobby project, now if my work would just let me work on this instead of the code they need I could make some progress :) I must say, it's a bit more fun doing a project that people use, just just line of business apps. But I digress..  here is what I see as road map/priorities going forward. If you look at my list #3 will 

1. FIX bugs!  
2. Performance.. Make it go faster, user less memory!

3. Finish my GIT service. So.. if you look in the repo .. I started to pull out the git logic in a static class called RepositoryManager. So what I did here was I started to pull out all the logic to manage the git repo in this static class.. So so you want the repo for a file at path X .. You ask the RepositoryManager for repo for file X.. It checks is storage for the repo, if it is there it returns the reference, if not it creates a new repo and returns that.. The class it returns is a GitRepository class.  The GitRepository class is responsible for all the git commands(Or it will be when complete) . I now also monitors the git repo for changes, and raises and event.  The RepositoryManager listens to all the GitRepository events and will re-raise them. So the SCC Provider and GIT UI service is getting away from having any direct access to the git repo..

What does that mean.. well for example previous to 1.4.2 the scc provider started a file watcher to monitor for changes.. I moved that out of the scc provider and put that into the GitRepository.  The scc provider just waits for an event from the RepositoryManager. Also the UI, say the Diff Window would ask the SccProvider for the current repo. Now it’s not 100% out of there, but for version 1.4.3, the UI wil ask the RepositoryManager for the current repo. Then I will rinse repeat until the UI and SccProvder no long know about each other (decoupling YEAH!) Anyway this should move me towards the path of merging.. 

4. What to do after this, is still a bit unknown.. Merge my code to the other git tool? Merge the Git Tools UI to my code? Or something more crazy.. a selective pull to a new project. In the grand scheme of things.. a new project might be best, but take the longest. There is a lot of clean up that could happen.. 

So when I started this.. version 1.3.1 I did a very quick and dirty move to 2015.. I did it just because I wanted the SCC provider back and loved the work @yysun had done. Then a buddy asked if he could use it, so I decided to put it where anyone could use it.. Then noticed a few bug myself, other people asked for fixes.. I did mean to cause confusion :) But now I’ve done it.. It’s fun to do.. I like that people are using it and generally like it.

**Comment by jzoss** [comment]
@yysun I do have a question.. That split button the the pending changes window. The one you do for TGit.. How did you do that.. I can figure it out.

**Comment by yysun** [comment]
@jzoss, the button is defined in the .vstc file to have flags to enable dynamic menu

<CommandFlag>DynamicItemStart</CommandFlag>
<CommandFlag>DefaultInvisible</CommandFlag>
<CommandFlag>FixMenuController</CommandFlag>

And in the package code, dynamically add the menus

for (int i = 0; i < GitToolCommands.GitTorCommands.Count; i++)
{
    cmd = new CommandID(GuidList.guidVsGitToolsPackageCmdSet, PkgCmdIDList.icmdGitTorCommand1 + i);
    var mc = new MenuCommand(new EventHandler(OnGitTorCommandExec), cmd);
                    mcs.AddCommand(mc);
}

The event handler is in OnGitTorCommandExec.

**Comment by wilhen01** [comment]
Didn't even know about Git Tools until I read this thread. Just installed it and tried it out...performance compared to Git Source Control Provider is *dreadful*. Visual Studio hanging for 3 seconds every time I change a file? No thanks. I don't know if that's something specific to the plugin implementation or whether it's the underlying Git Provider from MS that's at fault but either way it's pretty much unusable for me.

**Comment by jzoss** [comment]
@wilhen01 Performance is a big concern for me.. It's what I have been spending mos of my time trying to improve. The first version I put out 1.3.1 was a direct port of the old code basically, it performance was not all that good, just because it was created for an older version of VS and it was done the way you did things for those versions. 1.4 did improve performance a bunch, but it broke lot's of stuff. 1.4.1 and 1.4.2 fixed most of those bugs..(I Hope) In fact the next version I am working on 1.4.3 is really all about performance. The biggest change is getting rid of the auto-update loop, and only updating file status for the files that have changed. But since 1.3.1 I have been working redoing the core of the extension .. making it faster, cleaning up the code. Lot's of converting to async. Anyway, if these project get merged.. which I am not 100% sold on yet, because they are different I can say 2 things.. First the SCC provider is not going away.. If I can figure out a way to disable the provider for those who what to use the ms git provider or something else.. I will do that.. But I really like using Tortoisegit, using the same git interface in VS and explorer is the way to go IMHO :) Second performance will still be  more important than features, so when merging I will use the faster core code I am developing now, and If I can't bring in a feature from Git Tools without kill performance, I either won't or I will rewrite.. 

On a side note.. I have I have setup a CI [build](https://ci.appveyor.com/project/jzoss/git-source-control-provider) on AppVeyor. So feel free to grab the latest build and try in out.. You can always revert back to the release or update the next time if you want.. But you can see where things are going.. It's should not be too broken.. but it could be..

**Comment by PureKrome** [comment]
Hey @jzoss - i've disabled the plugin since I grabbed the latest (beta) release (from GH, not the offical download). It's been handing my VS. With Resharper disabled, it's not THAT noticable .. but with R# enabled - it's not good at all. I might have to revert BACK to the latest public release.

I've been holding off on reporting this because I don't know how to get an accurate repo of the issue (to help debug/resolve this). I've not been able to :(

**Comment by jzoss** [comment]
@PureKrome So you mean.. VS is freezing or something when you have resharper installed? I think I may be seeing the same thing.. I just pushed some updated code..so there is a new build.. cleans up a lot more bug and stuff.. You can try that one.. It seems better to me. I'm a bit worried that my file watchers and R# filewatchers are getting mad at each other.. The good news is the newest build.. the file are wicked fast.. If you could it a try.. it no better switch back to the release... I still have a bit more work before beta 1 of 1.4.3

**Comment by PureKrome** [comment]
@jzoss yep - that's what I ment.

i'll download the (newest) latest, again .. and keep u posted.

**Comment by jzoss** [comment]
Sorry.. Check this link https://ci.appveyor.com/project/jzoss/git-source-control-provider.. Get the latest... I had no idea the issue.. Then drove home and I think I got it.. If I'm right and you get the latest and have a proper git ignore (use the update gitignore in the pending changes window) I think it will go away.. And I can put in a proper fix in.

**Comment by teebee76** [comment]
Wow,  this is so cool.  Almost can't wait until tomorrow to get back to work and install the ci-build :)


-------- Original message --------

**Comment by PureKrome** [comment]
I'm pretty sure I have the version from CI.

-> open sln.
-> nothing listing in the CHANGED FILES list. I have one file changed (i did this before I opened VS).
-> used TortoiseGIT to commit.
-> VS crashed :/

spider sense is giving me the feeling that might not be good.

Also -> maybe this convo should be in another thread IMO.

**Comment by jzoss** [comment]
@PureKrome i was thinking the same. Anyway you can make a new bug.. Or if you have any suggestions. I will look at it in a 2nd computer in a bit. Also if you check out the version of the plugin in visual studio.. It gets set in the c.I. build .. So the last ci build was 1.4.2.31 .. If you don't make a bug I will when I get a few minutes

**Comment by wilhen01** [comment]
@jzoss performance under Git Source Control Provider 1.4.2 is really good for me, miles better than what I experience with Git Tools / MS Git provider. Great work :+1: 

It would be neat if the projects could be merged from the functionality point of view but I thoroughly agree with you re: performance; if you can't get all the features in without sacrificing performance then don't do it!

Cheers,
Henry

**Comment by jzoss** [comment]
@teebee76 @PureKrome @wilhen01 .. and anyone else who might be interested.. The [PreRelease]( https://github.com/jzoss/Git-Source-Control-Provider/issues/17) thread and try out the new build for me.. Help me find bugs .. all that stuff

**Comment by jzoss** [comment]
@wilhen01 @NightOwl888 @ddobrev @yysun -- Hi guys not sure if any of you have been paying attention to the #17 thread.. or if you still use the plugin.. Anyway, the final (hopefully) RC is posted in the release tab.. It is not cleaned up enough to merge it with the other project yet, but this is the first big step to that. Anyway the more tester the better.. if you are feeling like an adventure.

**Comment by yysun** [comment]
@jzoss thanks a lot! I will have 3-4 people to test the RC.
In terms of the code, do you want me grant you contributor so that you can
merge to the main stream?

**Comment by jzoss** [comment]
So.. Release 1.5 is out ..  I figured we could talk about merging.. so brief history.. Back when VS 2015 RC came out, I jumped on and looked for my favorite git scc provider and it was not there.. The original author released git tools, and I tried and it was ok, but it was missing the solution explorer integration. So I asked the original author ( @yysun  ) if he was planning on putting that in and he said this tool was made to run next to the ms git provider.. So I was ok with that.. I understood what he wanted .. but I missed the old way :)

Ok.. so then I forked and all this craziness happened. Then people ask , why are there 2 projects..

Simple Answer : Git Tools is a extension to add extra functionality to VS 2015. This project is a Source control extension that adds extra functionality to VS 2015. That does not sound like a big difference, but it sorta is.. Being a SCC provider means solution explorer integration and no other plugin in VS is monitoring the state of the project.

I am pretty open to suggestions, but I have a few requirements if we are going to merge. I am honestly fine making them 1 project or keeping them separate. 

1. **The SCC Provider needs to be part of it. **So if we want to be able to use it with the MS Git Provider we need to figure out a way to enable and disable it, while still keeping the pending changes window, etc. 

2. **We have to keep it clean **and remove the Git Diff Margin tool from the extension.. It's a fine extension but it's sorta a nightmare to try to keep it updated with the official version.. We can just have people install the official version. 

3.** We can't degrade performance **... I spent way too much time figuring out threading and exceptions in com objects :) So the remaining code in Git Tools  needs to be refactored a bit. 

So.. the way forward and where is everything now.. So.. without going into too much detail.. there are 3 components that are very important to all this.. The BasicSccProvider.cs class.. this is the main plugin class.. think of it as the class with the public static void main class. It is turn creates 2 more important classes.. The PendingChanges windows and the SccProviderService (this is the SCC provider part)

So if we merge.. v 1.5 was a big step in that direction.. I was most worried about refactoring and performance, but as part of the code clean up it I cleared some major code issues. A big issue was that all three of the components I mentioned above were very tightly coupled. The SccProviderService called update function on the pending changes, the PendingChanges windows called update on the service, the Provider class called update on both, all at different times.. And that was just one example. Anyway, I clean up a lot of that.. It is far from perfect right now, but a major step in that direction.   ( @yysun BTW I mean no offense about your code. I think you rock, and I was reading what I had written and thought I may have come off a bit blunt.)

Other things I did to make the merge easier.. I reused a lot to the git api enums and method names from the git api in git tools.. I rewrote all the code behind it but kept the interface.. for the most part. I also copied the GitUI external app that runs from git 

So.. what's next.. if we want to merge .. Well.. truth is.. not 100% sure.. 

So I think first it is to refactor the SccProviderService into 2 services. Truth is we still need a lot of what it does to keep the pending changes working.. It monitors the solution explorer so it knows when projects are loaded, unloaded.. It keeps a cache of files in the project to avoid unnecessary com interaction, and a bunch of other things.. Anyway it would need to be 2 services, one that IVsSccProvider and all the glyph management and one that handles all the solution events and maintains cache of files and their state.. This is probably a good idea in terms on maintainability regardless of merging the plugins.   

Second would be to work on seeing if we can have a plugin be both a scc provder and not a scc provider. Not sure how to do that yet.. 

Last thing I would like opinions on is this.. .Say I have maybe 10 hours a week to work on this.. is merging them together more important than adding new cool features? 

Anyway.. that got a bit long winded .. so that's the state of everything.. What does everyone think ? @NightOwl888 You started this, what's your opinion? @teebee76 @PureKrome You guys always have good ideas, feel free to weigh in.. Also #30 is open for talk about the next release.

**Comment by ddobrev** [comment]
@jzoss I am afraid I can only give an opinion on the general issue because I am not familiar enough with the area. It always seems like too much work to merge two projects, and it always looks much easier to make decisions alone rather than agreeing on them with other people (I mean @yysun - as the author of the other project). However, in the long term the manpower behind the project is more than doubled because, you know, the whole is greater than the sum of its parts. So I assure you that it is definitely worth it to combine the two efforts so that you and @yysun can then collaborate on the same code. On top of this comes, of course, the facts that new users would not get confused as to what to use and that all potential contributors would channel their strength into a single project. So over time, as stated above, the manpower would become more than tripled, more than quadrupled, more than quintupled and so on.

**Comment by yysun** [comment]
Thanks @jzoss. Further decompose the two projects, there are several modules:

1. GitApi - interface to Git commands
2. Pending Changes Window - VS Tool Window => reference to 1
3. File/project/solution change detection inside VS
4. SCP glyphs and Solution Explorer Integration
5. GitGui (WPF) - the History viewer => reference to 1
6. GitSCC (vsix) = 1 + 2 + 3 + 4
7. GitTools (vsix) = 1 + 2 + 3 

Recommandation:
I would like to have them grouped into individual GitHub projects and link them using Git submodule:

- GitApi (class lib)
- Git Pending Changes for VS (class lib)
- GitScc (vsix)
- GitTools (vsix)
- GitGUI (WPF)

GitScc, GitTools and GitGUI link to GitApi and Git Pending Changes projects using Git submodule.
Feasible, @jzoss?

History and thoughts:
In GitScc, GitApi combines ngit and git command shell. In GitTools, I tried only using command shell in order to simplify git file status analysis especially when taking considerations of git ignore file, but there was performance issue. I planned to try libgit2sharp. @jzoss has already made the change!

InGitScc, file change detection (3 + 4) is based on VS idle events and VS file/solution change hooks. It is very complicated COM and threading related. GitScc worked in VS2008-VS2015. To make it work was a nightmare. In GitTools (3 only), I tried using FileChangeWatcher and Timer, same way in GitGUI, but there was stability issue inside VS when VS has other extensions like Reshaper.

So, the idea of recommendation above was:
1 and 2 be shared in two projects easily. 
GitScc has unique 3 + 4 crazyness - COM and threads. It works well now a least.
GitTools has 3 implemented differently. We can try to solve the performance and stability issues without or less COM and threading. There are many changes in every versions of VS. I am dreaming next version of VS there is an easier API to hook into.  GitTools can be the place for exploring new technologies.

**Comment by yysun** [comment]
One more thing. Just like @NightOwl888 said, forks create confusing and difficulties. I am open to make anyone who wants to contribute be collaborators to the original github projects. @jzoss, I have added you. Now you can merge this fork into the original project. Going forward push changes w/o pull requests and no syncing to upstream.

@jzoss, you can continue publish vsix to VS extension gallery for VS2015. My old vsix will be left there for VS2013. I won't upgrade it for VS2015 to avoid confusions to end users.

**Comment by NightOwl888** [comment]
> Last thing I would like opinions on is this.. .Say I have maybe 10 hours a week to work on this.. is merging them together more important than adding new cool features? 

Given that merging the projects together will enable other developers to contribute their efforts to a singular place (even if those efforts are just reporting bugs), it will make the whole project run smoother. So, my vote is to spend those 10 hours a week merging the projects first as that will lead to a better experience down the line and a better piece of software with fewer bugs.

Adding new features is great, but for my own use just the ability to 1) list the files that changed 2) click each file to see the diff of what changed 3) see how the file changed (added, modified, deleted) and 4) check boxes to filter which files to commit are enough reasons to use it. Anything else is just icing on the cake.

@yysun - Agree that things should be well organized, but if you are going to break into different GitHub projects, it might be better to use NuGet (via a feed service like [MyGet](http://myget.org/)) to manage the DLL dependencies rather than using submodules. I have had some experience with submodules and managing them is not that straightforward, which will no doubt lead to fewer code contributions. NuGet has the added advantage that you don't have to upgrade every project to the latest version of the dependency at once, which will make it easier to upgrade each project as needed instead of pushing potentially breaking changes to all of the projects at once.

That said, I have never used NuGet in conjunction with COM components and I am not sure whether that will be problematic or not. Certainly COM has its own issues with versioning to deal with.

**Comment by PureKrome** [comment]
My opinions from the posts above,

- Merge the projects so there's one VS Gallery download.
- Splitting projects up into separate Repos: Maybe. I can see the 2x class libraries being in one repo, the rest in another.
- Don't submodule. urgh. NuGet all the things.
- Don't really care/need new features. Main thing here is to see change files (and the diff in window) and the commit. The rest, just use TGit directly or cli.

**Comment by jzoss** [comment]
Man.. I leave for a few days and people comment.. So.. Where to start..

@yysun Threading is a giant PITA. So, we should talk.. I redid all the threading in 1.5.. it took a while but is now unbroken. So.. basically it is uses an asynchronous event model and the new threading model in VS to do all it's work. It took a while and you need to be careful to do it everywhere.. Perhaps we can chat elsewhere about it, because it is complicated. Anyway, I'm pretty sure this threading will be pretty stable for the next few vs versions, because it's mostly uses standard async/await. However if we follow the rules and make sure all the code follows the rules.. it's pretty easy.. much better than before.

Because of the new threading... It is possible to make this work in Vs 2013.. but nothing earlier. So we could port it back to 2013... pretty easily, but we may want to update the old version to not support 2013 anymore..

@NightOwl888 + @PureKrome : I agree I also hate submodules.. 
Also we can split the repos if we want.. Not sure we need that many.. but let me test.. maybe we should make a organization.

**Comment by yysun** [comment]
@jzoss Is it possible to make the Pending Changes Tool Window visible working all the time even the GitScc is not selected as Source Control Provider under Tools | Options | Source Control?

If yes, all troubles go away.

**Comment by jzoss** [comment]
@yysun Yea probably.. I need just need to separate the sccprovider service with the solution service ... Should not take me that long.. once I get a bit of time.

**Comment by ddobrev** [comment]
Apologies if this has already been mentioned but it seems the Microsoft Git Provider has serious problems with performance: http://stackoverflow.com/a/32576012, http://stackoverflow.com/a/32581271. If this is true, then the merged project would be better off using its own provider unlike @yysun 's code.
Having said that, I've been having VS consume 50 and more percent CPU quite often lately. Has perhaps Git SCC already switched to MS's provider internally?

**Comment by jzoss** [comment]
@ddobrev GIT scc has not moved to Ms git.  I have noticed increased memory usage in Visual Studio,  but I don't think its related to git scc.  I haven't noticed any increased memory in the profiler,  but I can take a closer look.

**Comment by jbestrom** [comment]
I don't think the increased memory/cpu is from this.

Issues like https://connect.microsoft.com/VisualStudio/feedback/details/2544045/low-memory-detected-full-solution-analysis-disabled-for-this-solution-on-roslyn-code-analyzer-enabled-projects if you are on update 2 are causing all kinds of headaches for me at least.

**Comment by ddobrev** [comment]
Thank you very much for this information, I am definitely going to track the fixing of this VS bug.

**Comment by jbestrom** [comment]
NP it is a pain in the butt when things like that show up. We are unable to move to VS2015 for production stuff cause of constant lock ups and slow downs.

**Comment by jzoss** [comment]
closing as it's not really a bug.
