### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by cocosip** [jzoss/Git-Source-Control-Provider#68]
vs2015 change the source control  to svn , when i create a new project, it has a error!
"object reference not set to an instance of an object"
disable the Git-Source-Control-Provider,error disappear.

**Comment by jzoss** [comment]
What svn plugin are you using ?

**Comment by cocosip** [comment]
AnkhSvn+TortoiseSVN

**Comment by jzoss** [comment]
Have not been able to recreate yet.. That does not mean anything really because I have found visual studio setups are so different. 
So does this happen every time you start a new project? With every type of project? 
Were you in a git project, then switched or did you open a new VS2015 instance and switch ans start a new project ?
